hydra:
    launcher:
        cpus_per_task: 4
        gpus_per_node: 0
        tasks_per_node: 1
        timeout_min: 60
        mem_gb: 4
        name: ${hydra.job.name}
    run:
        dir: /checkpoint/${env:USER}/outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
    sweep:
        dir: /checkpoint/${env:USER}/outputs/${hydra.job.name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
        subdir: ${hydra.job.num}_${hydra.job.override_dirname}